steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/okf-md-master', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/okf-md-master']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'okf-md-master',
      '--image', 'gcr.io/$PROJECT_ID/okf-md-master',
      '--platform', 'managed',
      '--region', 'europe-west1',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--port', '8080']
images:
  - 'gcr.io/$PROJECT_ID/okf-md-master'
